# ============================================================
# Herbaceous plant productivity parameters
# ============================================================

GPPmax_herb: 4.0         # Maximum daily GPP (g C m-2 d-1)
Q10: 2.0                 # Temperature sensitivity of photosynthesis
Tref: 20.0               # Reference temperature (°C)

theta_opt: 0.3          # Optimal soil moisture for plant productivity

maint_resp: 0.002        # Maintenance respiration (g C g C-1 d-1)
growth_resp: 0.25        # Fraction of GPP lost to growth respiration

a_root_herb: 0.5        # Root allocation fraction (ANPP:NPP = 0.55)

# ---- Turnover and flux rates ----
k_litterfall_ann: 0.35
k_litterfall_herb_ann: 1

k_mort_leaf: 0.00005479    # 0.02/365
k_mort_wood: 0.00006849    # 0.025/365
k_mort_root: 0.00021918   # 0.08/365
k_exudate: 0.00002740     # 0.01/365
winter_root_act_prop: 0.01
root_dormancy_temp: 5

# ---- Optional removals (set to zero if unused) ----
leaf_harvest: 0
wood_harvest: 0
root_harvest: 0

herbivory_leaf: 0
herbivory_wood: 0
herbivory_root: 0


# ------- Root herbivory ---------
c_rootherb: 0.05
d_rootherb: 4
a_rootherb: 0.4
p_rootherb: 0.37 # default of 1
E_root_herb: 0 # default of 0
k_exudate_intercept: 0.00002740
k_exudate_slope: 0
